### ISSUE TITLE
Compatability with latte 2.9.0 ($this->blockQueue removed)

### ISSUE THREAD

**Issue by ales-zrak** [nextras/datagrid#102]
`$this->blockQueue` was removed in new version of latte: https://github.com/nette/latte/releases

This results in row action column not being displayed as condition `isset($this->blockQueue["row-actions"])` in `Datagrid.latte` is always false.

It seems that using `$this->hasBlock("row-actions")` in `Datagrid.latte` works fine - see pull request https://github.com/nextras/datagrid/pull/101 🙂

**Comment by hrach** [comment]
Thanks for report & fix, fixed in https://github.com/nextras/datagrid/commit/6d1d222ea49891150780694018f0ececf3a08a58
