### ISSUE TITLE
DESC sort

### ISSUE THREAD

**Issue by aleswita** [nextras/datagrid#37]
If you have default sort in column by DESC, like below

``` php
$grid->addColumn("revision","Revize")->enableSort($grid::ORDER_DESC);
```

data in grid table sorted are OK, but link for change sort from DESC to ASC is without function

**Comment by vakvas** [comment]
Hi, please.. id this behavior solved?
Thanks a lot !

**Comment by hit-cz** [comment]
Just looked into it and it seems that there is something wrong whne creating link to sort signal. This is probably side effect of another bug.

Let's have an example scenario:
- Column 1 sorted DESC
- Click on column 2 heading
- Sorted column is column 2 (this is ok), but sorting status is set to NULL

This does not make sense to me. Column 2 should be sorted ASC everytime we change sorting to this column from some other column.

I will try to look into it in few days, I think that fixing this behaviour could also fix this bug.

**Comment by hrach** [comment]
Guys, are you able to do a pullrequest?

**Comment by janmottl** [comment]
I'm not familiar with code enough to be able to fix it. I suppose that problem is that it's not distinguished between first rendering and rendering after users change of sorting. It's necessary to detect user change of ordering and suppress default ordering.

**Comment by hrach** [comment]
So, it's fixed!

**Comment by janmottl** [comment]
Thanks. špica :)
