### ISSUE TITLE
conflict in case of nette.ajax use outside of grid

### ISSUE THREAD

**Issue by LeonardoCA** [nextras/datagrid#39]
if I use $.nette.ajax call for something else while having nextras.datagrid.js in project, following code gets executed
```php
before: function(xhr, settings) {
		this.grid = settings.nette.el.parents('.grid');
	},
```
and it ends up with error

Uncaught TypeError: Cannot read property 'el' of undefined

I believe that it should be considered that settings.nette.el does not have to exist?

**Comment by vojtech-dobes** [comment]
`settings.nette` doesn't have to exist is precise answer.

**Comment by hrach** [comment]
@LeonardoCA Thanks for reporting. Will you send PR?
