### ISSUE TITLE
Možnosť nastaviť primary key ako callback

### ISSUE THREAD

**Issue by brosland** [nextras/datagrid#44]
Zdravím,

bolo by možné pridať možnosť nastaviť primary key ako callback?

Pracujem s Doctrine a keďže výstup pre jeden riadok môže vyzerať aj takto:
http://forum.nette.org/cs/22758-doctrine-kdyby-doctrine-queryobject-vytiahnutie-dat-do-gridu 
potreboval by som tam dať takýto callback:
```
$datagrid->setRowPrimaryKey(function($row)
{
	return $row[0]->getId();
});
```
Bolo by to možné pridať?

**Comment by hrach** [comment]
To to asi fakt ne. To, ze ten vystup vypada tak tragicky je smutne, ale nevim co vis s tim. Pripadne si muzes nadefinovat vlastne getter na ty property, ktery u nejakych kllicu se bude takto pozadovane chovat.
