### ISSUE TITLE
Pri vlastnom vykresľovaní buniek, nevytvárať premennú $cell

### ISSUE THREAD

**Issue by brosland** [nextras/datagrid#45]
Zdravím,

Bolo by možné odstrániť automatické vytváranie premennej $cell pri vlastnom vykresľovaní bunky?

Pracujem s Doctrine a keďže výstup pre jeden riadok môže vyzerať aj takto:
http://forum.nette.org/cs/22758-doctrine-kdyby-doctrine-queryobject-vytiahnutie-dat-do-gridu

Datagrid sa pokúsi vyhľadať premennú, no nenájde a vyhlási chybu. Pritom mne by úplne stačilo si tú premennú nájsť sám, pokiaľ si vytváram vlastné vykresľovanie.

Bolo by to možné toto upraviť (napr. aspoň jej vytvorenie podmieniť)?

```
{var $cell = isset($row[$column]) ? $row[$column] : NULL}
```

Tým by bola udržaná spätná kompatibilita a zároveň pridaná voľnosť si vo výslednom rendery nájsť premennú v $row.

**Comment by hrach** [comment]
Co mi to tady pises? Vzdyt se podivej, ze se to taha pres metodu getter, 
`{var $cell = $control->getter($row, $column->name, FALSE)}`, ktere se predava false, tj. ta bunka neni povinna, viz. https://github.com/nextras/datagrid/blob/0cca71f6ee66bb00759b67b61dc67adb950a7e57/src/Datagrid.php#L369-L384
Na druhou stranu je tam videt bug, ze se vlastnimu getteru nepredava to $need, takze on nemuze vedet, jestli hazet exception nebo ne. Feel free to make a PR! :)

**Comment by brosland** [comment]
Sorry, za ten snippet kódu, to bolo len tak zbrucha vymyslené, ako by sa dalo podmieniť vytváranie premennej $cell :-). Nemyslel som to doslovne.

**Comment by hrach** [comment]
Takze ted opravdu zavisi na tve implementaci getteru. Ta ma k dispozici treti parametry need, ktery prave muze zohlednit issetem existenci a vratit nul.

**Comment by hrach** [comment]
Diky za report!
