### ISSUE TITLE
New Feature: Datagrid delete row action

### ISSUE THREAD

**Issue by insekticid** [nextras/datagrid#48]
Datagrid supports inline editing, but if you want another action, you have to code it by yourself.
I think that 2 basic actions are edit and delete.

What do you think?

**Comment by george-oakling** [comment]
I personally do the delete and other functions by extending datagrid like this:
```php

namespace App\Components;

use Nette\Utils\Callback;

class Datagrid extends Nextras\Datagrid\Datagrid {
	
	private $deleteCallback;
	
	public function handleDelete($primary) {
		Callback::invokeArgs($this->deleteCallback, [$primary]);
	}
	
	public function setDeleteCallback($callback) {
		$this->deleteCallback = $callback;
	}
	
}

```

Then, simply add this definition to the component process creation:
```php
$grid->setDeleteCallback($this->deleteRow);
```

and then you have to code just deleteRow($primary) function and add this after edit button in datagrid.latte definition (this is bootstrap version):
```html
<a href="{link delete! $primary}" data-datagrid-edit class="ajax btn btn-warning btn-xs">Delete</a>
```

**Comment by insekticid** [comment]
yes, it is supereasy to extend datagrid, but in my opinion, two basic operations are edit and delete and should be added

**Comment by hrach** [comment]
Well, the edit is there because it's pretty hard to to, but the delete should be quite easy :-) I would like to focus more on the multirow actions, so I'm closing this. I hope you understand that such functionality wouldn't bring much added value in comparision on complexity and documentation.
