### ISSUE TITLE
Nette 2.4 Support

### ISSUE THREAD

**Issue by igorpocta** [nextras/datagrid#53]
Accessing methods as properties via $obj->processForm is deprecated in C:\xampp\htdocs\NETTE2.4\vendor\nextras\datagrid\src\Datagrid.php:462

**Comment by hrach** [comment]
PRs are welcomed! I've stared working in support nextras/latte-macros for Nette 2.4, that's actually also neede and seems to be a bigger task :-)

**Comment by simPod** [comment]
`Thrown exception 'Call to undefined method Latte\Compiler::getTemplateId().'` v nette 2.4

musel jsem v `composer.json` requirovat `dev-master` pro `nextras/latte-macros`. Muzu poslat PR, ale mozna by byl lepsi novej release `latte-macros`?

https://github.com/LidskaSila/datagrid/commit/616c496c6e9f6a14a151c1394b4c1915a139542d

**Comment by hrach** [comment]
Fixed by https://github.com/nextras/datagrid/commit/49b98b7e7f39363af35dde54dfb203a6c8486868
