### ISSUE TITLE
Doplnit dokumentaci nebo dát examples někam na github

### ISSUE THREAD

**Issue by novotnej** [nextras/datagrid#61]
Někdo kdo přijde k Nette poprvé, nebo nikdy nepracoval s něčím podobným bude mít docela problém sám vyzkoumat, jak tu komponentu vlastně dostat do šablony a vykreslit.. (A to samé teda by chtělo i pro BS3 renderer v nextras/forms)

**Comment by milsorm** [comment]
Navic zjistit, ze existuje {define empty-result} jde az analyzou puvodni sablony :-)

**Comment by hrach** [comment]
Samples byly i driv, ale ne linkovane z readme. Ted nove v https://github.com/nextras/datagrid-demo a linkovane z readme.
