### ISSUE TITLE
Variable $template is deprecated

### ISSUE THREAD

**Issue by novotnej** [nextras/datagrid#62]
[ladenka.html.zip](https://github.com/nextras/datagrid/files/483208/ladenka.html.zip)

**Comment by hrach** [comment]
Current master do not use any  $template variable.

**Comment by novotnej** [comment]
I just installed it via composer with nette 2.4
"nette/nette": "~2.4",
"nextras/datagrid": "^2.1"

"minimum-stability": "stable"

You will probably need to update some dependencies...

**Comment by hrach** [comment]
Yes, to Nette 2.4 is compatible only master. So, try to use "nextras/datagrid": "@dev"

**Comment by novotnej** [comment]
Yes I assume this would solve the problem. But that's not the point - composer has dependencies exactly for this purpose - especially if you know that these versions are incompatible, composer wouldn't allow to install them, had the dependencies been declared properly..
