### ISSUE TITLE
Inline edit reduces the dataset to one row

### ISSUE THREAD

**Issue by maral** [nextras/datagrid#63]
Hi guys, first of all, thanks for this project, it's awesome and we use it often at Vcelka.cz ;)

Now, I think in previous versions the datagrid used to behave differently in regard to editting. When I used edit, all rows remained, but the edited was changed to inputs. Then after cancelling, the whole datagrid remained the same. However, with this version (e.g. [here](https://nextras.org/datagrid/examples/full)) when I select edit, all the other rows disappear, and remain gone even when I cancel the action, which I think is a bug. If not, then what was the idea behind that?

I would love to help fixing this, but I am not very good with ajax and partial snippet redrawing..

**Comment by hrach** [comment]
What does "this version" exactly mean?

**Comment by hrach** [comment]
Oh, you mean the demo? I believe the master should be ok...

**Comment by maral** [comment]
Okay, I'll try to upgrade. I wasn't sure if I'm doing something wrong, so I just checked the demo and saw the same problem, so I assumed it's how the things are. I might be good idea to update the demo's version.

**Comment by hrach** [comment]
Yeah, probably, I'm going to remove demos from offcial site and distribute them with the source-code. Btw, try the master.

**Comment by maral** [comment]
Okay, so I tried upgrading to master - with the same result, unfortunately. Whenever I do basic editing with the minimal setting via ajax, all other rows just disappear. I have tried changing almost everything and it still works odd like this. I am starting to believe it's a feature 😄.

I also found couple more things - at @bootstrap3.datagrid.latte, macro col-filter there is missing class "form-control" - it used to be there, no idea why it's gone (and the filter inputs look ugly without it).

Another thing I noticed - if you don't add filter form factory, the actions column is not rendered, even when it is defined in a template that is added by the method addCellsTemplate. The cause of the problem is, that the test for this column in Datagrid.latte uses `$this->blocks['row-actions']`, which are not defined. But as I found out, the block exists in `$this->blockQueue`. Now, I really don't understand the internals of Latte system, so I have no idea how these two arrays relate. My guess is, that the {import} macro does not put new blocks to `$this->blocks`, just to `$this->blockQueue`, because all blocks defined in Datagrid.latte are present in `$this->blocks` - only imported blocks are missing.

**Comment by hrach** [comment]
@maral 
- inline edit: Please, take a look at https://github.com/nextras/datagrid-demo. I cannot reproduce the missing rows when doing inline edit.
- styling of input: fixed
- row actions: already reported here: https://github.com/nextras/datagrid/issues/64

**Comment by hrach** [comment]
For now I would close is as cannot reproduce, feel free to reopen a provide more feedback :-) Thanks!
