### ISSUE TITLE
row-actions ignored if filter is not used

### ISSUE THREAD

**Issue by milsorm** [nextras/datagrid#64]
I have grid without filter but with row-actions block in my template.

Inside Datagrid.latte:

```
{var $hasActionsColumn =
    isset($this->blocks['row-actions']) ||
    isset($this->blocks['global-actions']) ||
    isset($form['filter']) ||
    (bool) $control->getEditFormFactory()
}
```

When dumped $this->blocks the row-actions is missing. If I create filter form, than $hasActionsColumn will be true (not from row-actions block existence) and I can see all row-actions. Without filter not.

Possibly $this->blocks cannot see MY row-actions but only default blocks in Datagrid.latte?

**Comment by milsorm** [comment]
My workaround inside Datagrid.latte:

```
	{ifset #row-actions}{var $hasActionsColumn = 1}{/ifset}
```

just after than code (because ifset can check existence of block better than $this->blocks).

**Comment by hrach** [comment]
Thanks for the bugreport and suggested fix!
