### ISSUE TITLE
Pokud nastavim default ordering, nelze již měnit pořadí ASC/DESC

### ISSUE THREAD

**Issue by janmottl** [nextras/datagrid#67]
Ahoj,
potřeboval bych nastavit defaultní řazení a aby uživatel měl možnost ho měnit.

Pokud nastavim default ordering, nelze již uživatelsky měnit řazení ASC/DESC
`        $grid->addColumn('objednavka_uid', 'Číslo')->enableSort($grid::ORDER_DESC);
`
bez default orderingu uživatelská změna řazení ASC/DESC funguje pěkně.
`        $grid->addColumn('objednavka_uid', 'Číslo')->enableSort();
`
Dá se to nějak řešit? Díky. Honza

**Comment by vakvas** [comment]
https://github.com/nextras/datagrid/issues/37

Už pár let, ale bohužel zatím nikdo neřešil :/

**Comment by janmottl** [comment]
Díky. Je to škoda :(

**Comment by hrach** [comment]
Thanks for linking the appropriate issue. I will close this. If you are able to do a pullrequest, it would be great and it will speed up the process of fixing this.
