### ISSUE TITLE
Include doesn't work

### ISSUE THREAD

**Issue by hrach** [nextras/datagrid#77]
See comment https://github.com/nextras/datagrid/commit/68189597f9dc7755c96356c155c4512e893b6534

**Comment by maral** [comment]
@hrach Could you please fix this bug? We use datagrid on production and each build we have to fix this line manually (include -> import)... Just revert commit 6818959, even though it doesn't solve #76, at least it wouldn't be broken.

**Comment by JanTvrdik** [comment]
reverted
