### ISSUE TITLE
Pridat podporu pro hromadne akce

### ISSUE THREAD

**Issue by hrach** [nextras/datagrid#9]
Zvazit moznost podpory pro hromadne akce

**Comment by michallohnisky** [comment]
:+1:

**Comment by romanmatyus** [comment]
Grid vyzera super, ale toto je klucova funkcionalita. Planujes to pridat?

**Comment by hrach** [comment]
Planuju, ale neni na to cast. Hlavne ma grid nejake bugy, takze treba je pridat testy a trochu to refactorovat a ofixovat.

**Comment by kocourPB** [comment]
:+1:

**Comment by honzanovacek91** [comment]
:+1:

**Comment by igorpocta** [comment]
:+1:

**Comment by petrf89** [comment]
Kezby se ty hromadne akce povedly. :+1: Pak uz to opravdu bude datagrid se "vsim, jak ma byt".
Zatim jsem si ho jen pretizil tak, aby podporoval export do XLS.

**Comment by mstrouhal** [comment]
👍

**Comment by hrach** [comment]
Work has started! https://github.com/nextras/datagrid/commit/2948fd3107f065ea61176f2fc855f89477e630ca Stay tuned!
